### PR TITLE
Updated the library being used (ISSUE#2)

### PR DESCRIPTION
**Pull request by ARTHURFLECK1828**
Due to shareplum being out of order , alternatively office365 library is put into use

### CODE REVIEW

**Review by PratikGarai — CHANGES_REQUESTED** [review]
Add requirements.txt

**Comment by ARTHURFLECK1828** [comment]
Added requirements.txt

**Review by PratikGarai — CHANGES_REQUESTED** [review]
Seems like you added your entire system's requirements files. I just want the one specific to the project.

**Comment by ARTHURFLECK1828** [comment]
My bad , corrected it now

**Review by PratikGarai — APPROVED** [review]
Looks all good

**Pull request merged**
